name: Release

permissions:
  contents: write

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            target: linux-x64-14.15.3
            output: clien-archiver-linux-x64
          - os: macos-latest
            target: mac-x64-14.15.3
            output: clien-archiver-macos-x64
          - os: windows-latest
            target: windows-x64-14.15.3
            output: clien-archiver-win-x64

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: |
          npm run build
          npx nexe lib/index.js --target ${{ matrix.target }} -o ${{ matrix.output }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ matrix.output }}${{ startsWith(matrix.output, 'clien-archiver-win') && '.exe' || '' }}
          asset_name: ${{ matrix.output }}-${{ github.ref_name }}${{ startsWith(matrix.output, 'clien-archiver-win') && '.exe' || '' }}
          asset_content_type: application/octet-stream
